version: '3.8'

services:
  cowbot:
    build:
      context: .
      target: cowbot-production
    environment:
      - CONTACT_URL=https://discord.gg/rtyA7rEugx
      - DEV_SERVER_ID=1138248283224027206
      - SERVER_URL=http://cowserve:5411
    env_file:
      - .env.docker
    depends_on:
      - cowserve
  cowsite:
    build:
      context: ./cowsite
    restart: on-failure
    environment:
      - SERVER_URL=localhost:5411
    ports:
      - 3000:3000
  cowserve:
    build:
      context: .
      target: cowserve-production
    restart: on-failure
    ports:
      - 5411:5411
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - QUEUE_URL=amqp://rabbit:rabbit@queue:5672/cowsay
      - SERVER_PORT=5411
    depends_on:
      - postgres
  cowserve_jobs:
    build:
      context: .
      target: cowserve-production
    command: cowserve consume
    restart: on-failure
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - QUEUE_URL=amqp://rabbit:rabbit@queue:5672/cowsay
      - SERVER_PORT=5411
      - PREVIEWS_DIR=/tmp/previews
    depends_on:
      - queue
  postgres:
    image: postgres:15.4
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
  queue:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
      - RABBITMQ_DEFAULT_VHOST=cowsay

volumes:
  postgres:
