version: '3.8'

services:
  cowbot:
    build:
      context: .
      target: cowbot-production
    environment:
      - BOT_TOKEN=TOKEN
      - SERVER_URL=http://localhost:5411
    depends_on:
      - cowserve
  cowserve:
    build:
      context: .
      target: cowserve-production
    ports:
      - 5411:5411
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - SERVER_PORT=5411
    depends_on:
      - postgres
  postgres:
    image: postgres:15.4
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres:
