services:
  cowsay:
    build: .
    ports:
      - 5411:5411
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - SERVER_PORT=5411
  postgres:
    image: postgres:15.4
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres:
